Django_Four/learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views


# TEMPLATE TAGGING
app_name = 'basic_app'


urlpatterns = [
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),


]

Django_Four/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls'))

]

Django_Four/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

Django_Four/learning_templates/basic_app/views.py
from django.shortcuts import render


# Create your views here.


def index(request):
    return render(request, 'basic_app/index.html')


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_template.html')

Django_Four/learning_templates/templates/basic_app/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>

</body>
</html>

Django_Four/learning_templates/templates/basic_app/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO INDEX</h1>
    <a href="{% url 'basic_app:relative' %}">Link to relative page</a>
</body>
</html>

Django_Four/learning_templates/templates/basic_app/other.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
<h1>WELCOME TO OTHER</h1>
</body>
</html>

Django_Four/learning_templates/templates/basic_app/relative_url_template.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}"> THE OTHER APP</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
</body>
</html>